"""
Internship Database
In production: replace with PostgreSQL / SQLite query
For demo: returns a curated list of realistic PM Internship Scheme listings
"""

from typing import List, Dict

INTERNSHIPS: List[Dict] = [
    {
        "internship_id": "PMI-2024-001",
        "company": "Tata Steel",
        "title": "Junior Manufacturing Trainee",
        "location_city": "Jamshedpur",
        "location_state": "Jharkhand",
        "stipend": 5000,
        "duration_months": 3,
        "sector": "manufacturing",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering"],
        "description": "Learn manufacturing processes in a steel plant environment",
        "tags": ["manufacturing", "steel", "production", "plant", "industrial", "engineering"]
    },
    {
        "internship_id": "PMI-2024-002",
        "company": "Infosys",
        "title": "Software Development Intern",
        "location_city": "Bengaluru",
        "location_state": "Karnataka",
        "stipend": 10000,
        "duration_months": 6,
        "sector": "technology",
        "is_remote": True,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering", "science"],
        "description": "Work on real software projects with experienced mentors",
        "tags": ["software", "coding", "technology", "computers", "programming", "IT"]
    },
    {
        "internship_id": "PMI-2024-003",
        "company": "State Bank of India",
        "title": "Banking Operations Intern",
        "location_city": "Lucknow",
        "location_state": "Uttar Pradesh",
        "stipend": 6000,
        "duration_months": 3,
        "sector": "finance",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["commerce", "arts"],
        "description": "Learn banking operations, customer service and financial processes",
        "tags": ["banking", "finance", "data", "numbers", "customer", "operations"]
    },
    {
        "internship_id": "PMI-2024-004",
        "company": "ICAR - Indian Agriculture Research Institute",
        "title": "Agriculture Research Assistant",
        "location_city": "Patna",
        "location_state": "Bihar",
        "stipend": 4500,
        "duration_months": 4,
        "sector": "agriculture",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["science", "other"],
        "description": "Assist researchers in crop improvement and farm management studies",
        "tags": ["agriculture", "farming", "outdoor", "crops", "research", "soil", "rural"]
    },
    {
        "internship_id": "PMI-2024-005",
        "company": "Apollo Hospitals",
        "title": "Healthcare Administration Intern",
        "location_city": "Hyderabad",
        "location_state": "Telangana",
        "stipend": 7000,
        "duration_months": 3,
        "sector": "healthcare",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["medical", "science", "commerce"],
        "description": "Support hospital administration, patient management and healthcare operations",
        "tags": ["healthcare", "hospital", "people", "administration", "medical", "patients"]
    },
    {
        "internship_id": "PMI-2024-006",
        "company": "Prayas NGO",
        "title": "Community Development Field Worker",
        "location_city": "Ranchi",
        "location_state": "Jharkhand",
        "stipend": 4000,
        "duration_months": 6,
        "sector": "ngo",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["arts", "other"],
        "description": "Work with tribal communities on education and livelihood programs",
        "tags": ["ngo", "outdoor", "people", "community", "tribal", "teaching", "rural"]
    },
    {
        "internship_id": "PMI-2024-007",
        "company": "Mahindra & Mahindra",
        "title": "Automotive Engineering Intern",
        "location_city": "Pune",
        "location_state": "Maharashtra",
        "stipend": 8000,
        "duration_months": 6,
        "sector": "automotive",
        "is_remote": False,
        "min_year": 3,
        "max_year": 5,
        "preferred_streams": ["engineering"],
        "description": "Work on vehicle design, testing and manufacturing processes",
        "tags": ["automotive", "manufacturing", "engineering", "vehicles", "design", "machines"]
    },
    {
        "internship_id": "PMI-2024-008",
        "company": "NDTV",
        "title": "Digital Media Intern",
        "location_city": "New Delhi",
        "location_state": "Delhi",
        "stipend": 9000,
        "duration_months": 3,
        "sector": "media",
        "is_remote": True,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["arts", "commerce"],
        "description": "Create digital content, social media posts and assist in news production",
        "tags": ["media", "computers", "people", "writing", "social media", "journalism"]
    },
    {
        "internship_id": "PMI-2024-009",
        "company": "NITI Aayog",
        "title": "Policy Research Intern",
        "location_city": "New Delhi",
        "location_state": "Delhi",
        "stipend": 10000,
        "duration_months": 2,
        "sector": "government",
        "is_remote": False,
        "min_year": 3,
        "max_year": 5,
        "preferred_streams": ["arts", "commerce", "law"],
        "description": "Research and data collection for national policy programs",
        "tags": ["government", "data", "research", "policy", "people", "numbers"]
    },
    {
        "internship_id": "PMI-2024-010",
        "company": "Sun Pharma",
        "title": "Pharmaceutical Research Intern",
        "location_city": "Vadodara",
        "location_state": "Gujarat",
        "stipend": 7500,
        "duration_months": 4,
        "sector": "pharma",
        "is_remote": False,
        "min_year": 3,
        "max_year": 5,
        "preferred_streams": ["science", "medical"],
        "description": "Assist in drug formulation and quality control research",
        "tags": ["pharma", "research", "healthcare", "chemistry", "laboratory", "science"]
    },
    {
        "internship_id": "PMI-2024-011",
        "company": "NTPC Limited",
        "title": "Power Plant Operations Intern",
        "location_city": "Korba",
        "location_state": "Chhattisgarh",
        "stipend": 6500,
        "duration_months": 3,
        "sector": "energy",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering"],
        "description": "Learn power generation operations and maintenance in a thermal plant",
        "tags": ["energy", "outdoor", "engineering", "electricity", "manufacturing", "plant"]
    },
    {
        "internship_id": "PMI-2024-012",
        "company": "Wipro",
        "title": "Data Analytics Intern",
        "location_city": "Chennai",
        "location_state": "Tamil Nadu",
        "stipend": 12000,
        "duration_months": 6,
        "sector": "technology",
        "is_remote": True,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering", "science", "commerce"],
        "description": "Work with data teams on business intelligence and analytics projects",
        "tags": ["data", "computers", "numbers", "analytics", "technology", "business"]
    },
    {
        "internship_id": "PMI-2024-013",
        "company": "Pradhan Mantri Kaushal Kendra",
        "title": "Skill Training Coordinator",
        "location_city": "Bhopal",
        "location_state": "Madhya Pradesh",
        "stipend": 5000,
        "duration_months": 3,
        "sector": "education",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["arts", "other", "commerce"],
        "description": "Help coordinate vocational skill training programs for youth",
        "tags": ["teaching", "people", "education", "training", "skills", "youth", "rural"]
    },
    {
        "internship_id": "PMI-2024-014",
        "company": "Flipkart",
        "title": "Supply Chain & Logistics Intern",
        "location_city": "Kolkata",
        "location_state": "West Bengal",
        "stipend": 8500,
        "duration_months": 3,
        "sector": "logistics",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["commerce", "engineering"],
        "description": "Learn warehouse management and supply chain operations at a leading e-commerce firm",
        "tags": ["logistics", "data", "manufacturing", "operations", "commerce", "numbers"]
    },
    {
        "internship_id": "PMI-2024-015",
        "company": "Hindustan Unilever",
        "title": "Rural Sales & Distribution Intern",
        "location_city": "Patna",
        "location_state": "Bihar",
        "stipend": 7000,
        "duration_months": 3,
        "sector": "fmcg",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["commerce", "arts"],
        "description": "Support rural distribution network and assist local retailers",
        "tags": ["fmcg", "outdoor", "people", "rural", "sales", "distribution"]
    },
    {
        "internship_id": "PMI-2024-016",
        "company": "Indian Railways",
        "title": "Civil Works Monitoring Intern",
        "location_city": "Jaipur",
        "location_state": "Rajasthan",
        "stipend": 5500,
        "duration_months": 4,
        "sector": "infrastructure",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering"],
        "description": "Monitor ongoing railway track and bridge construction projects",
        "tags": ["infrastructure", "outdoor", "engineering", "construction", "railways", "civil"]
    },
    {
        "internship_id": "PMI-2024-017",
        "company": "Byju's",
        "title": "Education Content Intern",
        "location_city": "Bengaluru",
        "location_state": "Karnataka",
        "stipend": 8000,
        "duration_months": 3,
        "sector": "education",
        "is_remote": True,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["arts", "science", "engineering"],
        "description": "Create educational content for school and competitive exam preparation",
        "tags": ["teaching", "computers", "education", "content", "learning", "writing"]
    },
    {
        "internship_id": "PMI-2024-018",
        "company": "Water & Sanitation Support Organisation",
        "title": "Rural Water Quality Field Intern",
        "location_city": "Ranchi",
        "location_state": "Jharkhand",
        "stipend": 4500,
        "duration_months": 6,
        "sector": "environment",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["science", "other"],
        "description": "Test and monitor water quality in rural villages under Jal Jeevan Mission",
        "tags": ["outdoor", "environment", "agriculture", "rural", "people", "research"]
    },
    {
        "internship_id": "PMI-2024-019",
        "company": "HDFC Bank",
        "title": "Financial Literacy Intern",
        "location_city": "Lucknow",
        "location_state": "Uttar Pradesh",
        "stipend": 6500,
        "duration_months": 3,
        "sector": "banking",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["commerce", "arts"],
        "description": "Conduct financial literacy workshops in semi-urban areas under PMJDY",
        "tags": ["finance", "people", "teaching", "banking", "rural", "data"]
    },
    {
        "internship_id": "PMI-2024-020",
        "company": "Amul (GCMMF)",
        "title": "Dairy Supply Chain Intern",
        "location_city": "Anand",
        "location_state": "Gujarat",
        "stipend": 5500,
        "duration_months": 3,
        "sector": "agriculture",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["science", "commerce", "other"],
        "description": "Learn dairy cooperative operations, cold chain and rural collection",
        "tags": ["agriculture", "outdoor", "manufacturing", "rural", "food", "cooperative"]
    },
    {
        "internship_id": "PMI-2024-021",
        "company": "Tech Mahindra",
        "title": "IT Support Intern",
        "location_city": "Pune",
        "location_state": "Maharashtra",
        "stipend": 9000,
        "duration_months": 6,
        "sector": "technology",
        "is_remote": True,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering", "science"],
        "description": "Provide technical support and assist in system administration",
        "tags": ["computers", "technology", "IT", "support", "networking"]
    },
    {
        "internship_id": "PMI-2024-022",
        "company": "District Collector Office - Muzaffarpur",
        "title": "e-Governance Intern",
        "location_city": "Muzaffarpur",
        "location_state": "Bihar",
        "stipend": 4000,
        "duration_months": 3,
        "sector": "government",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["arts", "commerce", "law"],
        "description": "Assist with citizen services, data entry and digital governance programs",
        "tags": ["government", "people", "data", "computers", "teaching", "administration"]
    },
    {
        "internship_id": "PMI-2024-023",
        "company": "Reliance Retail",
        "title": "Retail Operations Intern",
        "location_city": "Nagpur",
        "location_state": "Maharashtra",
        "stipend": 7000,
        "duration_months": 3,
        "sector": "retail",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["commerce", "other"],
        "description": "Learn retail store operations, inventory and customer service",
        "tags": ["people", "commerce", "retail", "customer", "operations", "numbers"]
    },
    {
        "internship_id": "PMI-2024-024",
        "company": "ISRO Outreach",
        "title": "Space Science Education Intern",
        "location_city": "Thiruvananthapuram",
        "location_state": "Kerala",
        "stipend": 8000,
        "duration_months": 2,
        "sector": "research",
        "is_remote": False,
        "min_year": 3,
        "max_year": 5,
        "preferred_streams": ["science", "engineering"],
        "description": "Support public outreach and science communication for space programs",
        "tags": ["research", "science", "teaching", "data", "computers", "education"]
    },
    {
        "internship_id": "PMI-2024-025",
        "company": "Assam Tea Board",
        "title": "Tea Estate Field Intern",
        "location_city": "Dibrugarh",
        "location_state": "Assam",
        "stipend": 4000,
        "duration_months": 4,
        "sector": "agriculture",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["science", "other"],
        "description": "Learn tea cultivation, processing and quality monitoring in Assam tea gardens",
        "tags": ["agriculture", "outdoor", "manufacturing", "food", "rural", "farming"]
    },
    {
        "internship_id": "PMI-2024-026",
        "company": "Decathlon India",
        "title": "Sports Retail & Community Intern",
        "location_city": "Guwahati",
        "location_state": "Assam",
        "stipend": 6000,
        "duration_months": 3,
        "sector": "retail",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["other", "arts", "commerce"],
        "description": "Engage with sports communities and support retail store activities",
        "tags": ["people", "outdoor", "retail", "teaching", "community", "sports"]
    },
    {
        "internship_id": "PMI-2024-027",
        "company": "ONGC",
        "title": "Oil Field Operations Intern",
        "location_city": "Sibsagar",
        "location_state": "Assam",
        "stipend": 7500,
        "duration_months": 3,
        "sector": "energy",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering", "science"],
        "description": "Assist in oil and natural gas exploration field operations in Northeast India",
        "tags": ["energy", "outdoor", "engineering", "manufacturing", "oil", "field"]
    },
    {
        "internship_id": "PMI-2024-028",
        "company": "CRY - Child Rights & You",
        "title": "Child Education Program Intern",
        "location_city": "Bhubaneswar",
        "location_state": "Odisha",
        "stipend": 4500,
        "duration_months": 6,
        "sector": "ngo",
        "is_remote": False,
        "min_year": 1,
        "max_year": 5,
        "preferred_streams": ["arts", "other"],
        "description": "Support children's education and protection programs in Odisha",
        "tags": ["teaching", "people", "ngo", "outdoor", "rural", "education", "children"]
    },
    {
        "internship_id": "PMI-2024-029",
        "company": "Zoho Corporation",
        "title": "Business Software Support Intern",
        "location_city": "Chennai",
        "location_state": "Tamil Nadu",
        "stipend": 10000,
        "duration_months": 6,
        "sector": "technology",
        "is_remote": True,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["engineering", "commerce", "science"],
        "description": "Support businesses using Zoho's CRM and productivity software",
        "tags": ["computers", "people", "technology", "data", "business", "software"]
    },
    {
        "internship_id": "PMI-2024-030",
        "company": "National Health Mission",
        "title": "Community Health Data Intern",
        "location_city": "Raipur",
        "location_state": "Chhattisgarh",
        "stipend": 5000,
        "duration_months": 3,
        "sector": "healthcare",
        "is_remote": False,
        "min_year": 2,
        "max_year": 5,
        "preferred_streams": ["science", "medical", "arts"],
        "description": "Collect and compile community health data under national programs",
        "tags": ["healthcare", "data", "outdoor", "people", "rural", "numbers", "research"]
    },
]


def get_all_internships() -> list:
    return INTERNSHIPS
